### ISSUE TITLE
Adding PaginationComponent to declarations breaks app

### ISSUE THREAD

**Issue by mjwheatley** [seiyria/ionic2-pagination#3]
From README
```
import { PaginationComponent } from 'ionic2-pagination';
// add PaginationComponent to `declarations` 
```
I am using Angular2-Meteor.
I get the following error after adding `PaginationComponent` to my declarations
```
Uncaught SyntaxError: Unexpected token export  // modules.js:140969
```

**Comment by seiyria** [comment]
You need to use a bundler or compiler to make this work correctly, such as babel or tsc.

**Comment by mjwheatley** [comment]
Please add to your readme.
