### ISSUE TITLE
How to pass in data any example or plunk?

### ISSUE THREAD

**Issue by vipulnagarwal** [seiyria/ionic2-pagination#4]
I am also facing the same issue as issue #2  can you just post a working plunk or fiddle or something.

I am able to have your pagination component but not able to connect it with my data.

And also it would be really helpful if you can give details of
{ page: number; what is page here
pageSize: number; what is pageSize here
rowCount: number; what is rowCount here
pageCount: number; what is pageCount here
}

**Comment by seiyria** [comment]
Please don't post the same comment twice. Closing for duplicate.
